spring.application.name=satelite-ingestion-service

# ---- Oracle FIAP ----
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
spring.datasource.username=${ORACLE_USER:rm559611}
spring.datasource.password=${ORACLE_PASSWORD:031290}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ---- Kafka ----
spring.kafka.bootstrap-servers=${KAFKA_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# ---- Spring AI / OpenAI ----
spring.ai.openai.api-key=${OPENAI_API_KEY:sua-chave-openai-aqui}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.embedding.options.model=text-embedding-ada-002

# ---- JWT ----
app.jwt.secret=${JWT_SECRET:spaceweather-secret-key-fiap-2026-gs-must-be-very-long}
app.jwt.expiration-ms=86400000

# ---- Swagger ----
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# ---- Actuator ----
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# ---- Cache ----
spring.cache.type=simple
